name: CI

on:
  push:
    branches:
      - main
      - release-*
      - fix/*
      - chore/*
      - feature/*

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{github.event.ref}}
        uses: actions/checkout@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"

      - name: Composer Install
        uses: "ramsey/composer-install@v3"

      - name: Check ECS
        run: |
          php vendor/bin/ecs check --config=config/phpecs.php

      - name: Check PHPStan
        run: |
          php vendor/bin/phpstan analyse --configuration=config/phpstan.neon --memory-limit=1152M

      - name: Check PHPUnit
        run: |
          php vendor/bin/phpunit --configuration=config/phpunit.xml
